### ISSUE TITLE
Remove deprecated pkg_resources usage

### ISSUE THREAD

**Issue by georgkrause** [georgkrause/language_data#3]
There is a pretty elegant solution in https://github.com/rspeer/language_data/pull/6 which should be ported before the next release

**Comment by georgkrause** [comment]
This cannot be done as long as we want to support python 3.8, I am therefore removing it from the Milestone

**Comment by pdhall99** [comment]
> This cannot be done as long as we want to support python 3.8, I am therefore removing it from the Milestone

[importlib-resources](https://pypi.org/project/importlib-resources/) could be added as an conditional dependency for python < 3.9, and then
```python
import sys

if sys.version_info < (3, 9):
    from importlib_resources import files
else:
    from importlib.resources import files
```

I can make the changes if you'd accept this as a solution?

**Comment by georgkrause** [comment]
Python 3.8 is only supported until October 31, so instead of adding complexity I'd prefer to only remove the deprecated function when we stop supporting python 3.8.
